using System.Globalization;
using System.Text.Json;
using AXS.Core.Grouping;
using AXS.Core.Models;
using AXS.Core.Parsing;
using AXS.Core.Storage;
using MongoDB.Bson;

namespace AXS.Tests;

/// <summary>
/// The .NET port must produce exactly what python/axs produces on the same raw JSON:
/// same coverage line, same event fields, and the same Mongo documents (same _id / ListingIdentity,
/// section, row, seats, quantity, prices...). Fixtures/expected_python.json was generated by the
/// Python code (tests vector, see dotnet/AXS/README.md).
/// </summary>
public class ParityWithPythonTests
{
    private static string Fx(string name) => File.ReadAllText(Path.Combine(AppContext.BaseDirectory, "Fixtures", name));

    private static JsonElement Expected(string eventId)
    {
        using var doc = JsonDocument.Parse(Fx("expected_python.json"));
        return doc.RootElement.GetProperty(eventId).Clone();
    }

    private static AxsResult Veritix()
    {
        using var ev = JsonDocument.Parse("{\"pageProps\":" + Fx("axs_1457730_event.json") + "}");
        var e = AxsParser.ParseEvent(ev.RootElement);
        var inv = new Dictionary<string, string>
        {
            ["price"] = Fx("axs_1457730_price.json"),
            ["sections"] = Fx("axs_1457730_sections.json"),
            ["offer_search"] = Fx("axs_1457730_offer_search.json"),
        };
        return AxsGrouper.BuildResult(e, inv, null);
    }

    private static AxsResult Marketplace(string eventId = "1623526") =>
        AxsGrouper.BuildResult(new Event { EventId = long.Parse(eventId) },
            new Dictionary<string, string> { ["mp_offers"] = Fx($"axs_{eventId}_mp_offers.json") }, null);

    [Fact]
    public void Veritix_coverage_matches_python() =>
        Assert.Equal(Expected("1457730").GetProperty("coverage").GetString(), Veritix().Coverage);

    [Fact]
    public void Marketplace_coverage_and_id_match_python()
    {
        var r = Marketplace();
        Assert.Equal(Expected("1623526").GetProperty("coverage").GetString(), r.Coverage);
        Assert.Equal(7588913, r.Event.MarketplaceEventId);
    }

    [Fact]
    public void Event_metadata_matches_python()
    {
        var py = Expected("1457730").GetProperty("event");
        var e = Veritix().Event;
        Assert.Equal(py.GetProperty("event_id").GetInt64(), e.EventId);
        Assert.Equal(py.GetProperty("name").GetString(), e.Name);
        Assert.Equal(py.GetProperty("venue_name").GetString(), e.VenueName);
        Assert.Equal(py.GetProperty("event_dt_local").GetString(), e.EventDtLocal);
        Assert.Equal(py.GetProperty("event_dt_utc").GetString(), e.EventDtUtc);   // "2026-10-04T23:00:00Z"
        Assert.Equal(py.GetProperty("event_tz").GetString(), e.EventTz);
        Assert.Equal(py.GetProperty("ticket_url").GetString(), e.TicketUrl);
        Assert.Equal(py.GetProperty("performer_ids").EnumerateArray().Select(x => x.GetString()).ToList(), e.PerformerIds);
        Assert.Equal(py.GetProperty("door_dt_utc").GetString(), e.DoorDtUtc);
        Assert.Equal(py.GetProperty("onsale_dt_utc").GetString(), e.OnsaleDtUtc);
    }

    [Theory]
    [InlineData("1457730")]
    [InlineData("1623526")]
    [InlineData("1623554")] // Sound of Music: 11 marketplace "ladders"
    public void Mongo_documents_match_python_one_by_one(string eventId)
    {
        var r = eventId == "1457730" ? Veritix() : Marketplace(eventId);
        var now = DateTime.UtcNow;
        var net = r.Listings.Select(l => AxsDocuments.ToDocument(r.Event, l, now)).ToDictionary(d => d["_id"].AsString);
        var py = Expected(eventId).GetProperty("docs").EnumerateArray().ToList();

        Assert.Equal(py.Count, net.Count);
        foreach (var p in py)
        {
            var id = p.GetProperty("_id").GetString()!;
            Assert.True(net.ContainsKey(id), $"python _id {id} missing in .NET output");
            var d = net[id];
            foreach (var key in new[] { "SourceEventId", "Section", "Row", "Seating", "Zone", "PriceClass", "SeatKeys", "OfferId", "Splits", "SplitRule", "StockType", "InHandDate", "LadderGroup", "PublicNotes", "SeatFeatures" })
                Assert.Equal(Str(p.GetProperty(key)), d[key].IsBsonNull ? null : d[key].AsString);
            foreach (var key in new[] { "LowSeat", "HighSeat", "Quantity", "PriceLevelId", "MinQuantity", "MaxQuantity", "QuantityIncrement" })
                Assert.Equal(Num(p.GetProperty(key)), d[key].IsBsonNull ? (decimal?)null : d[key].ToDecimal());
            foreach (var key in new[] { "Price", "TotalPrice", "FeePerTicket", "FaceValue" })
                Assert.Equal(Num(p.GetProperty(key)), d[key].IsBsonNull ? (decimal?)null : d[key].ToDecimal());
            Assert.False(d.Contains("IsResale")); // resale-ness is PriceClass (Primary / Resale / Marketplace)
            Assert.False(d.Contains("LadderSize")); // n = Quantity of the IsLadderMax listing
            foreach (var key in new[] { "AllowEmptySingleSeats", "RequireContiguousSeats", "IsLadderMax" })
                Assert.Equal(p.GetProperty(key).ValueKind == JsonValueKind.Null ? (bool?)null : p.GetProperty(key).GetBoolean(),
                    d[key].IsBsonNull ? (bool?)null : d[key].AsBoolean);
        }
    }

    [Fact]
    public void Every_seat_lands_in_a_listing()
    {
        var r = Veritix();
        Assert.Equal(756, r.Listings.Sum(l => l.Quantity));
        Assert.Equal(167, r.Listings.Count);
        Assert.All(r.Listings, l => Assert.True(l.PriceCents > 0));
        Assert.Equal(17, r.Listings.Count(l => l.IsResale));
    }

    [Fact]
    public void Ladders_are_labelled_and_nothing_is_dropped()
    {
        var r = Marketplace("1623554");
        Assert.Equal(44, r.Listings.Count);
        Assert.Equal(110, r.Listings.Sum(l => l.Quantity));
        Assert.Equal(11, r.Listings.Select(l => l.LadderGroup).Distinct().Count(g => g != null));
        Assert.Equal(44, r.Listings.Where(l => l.IsLadderMax == true).Sum(l => l.Quantity));
        Assert.All(Marketplace().Listings, l => Assert.Null(l.LadderGroup)); // AEW: no ladder
    }

    [Fact]
    public void Sold_out_marketplace_gives_zero_listings_and_a_note()
    {
        var r = AxsGrouper.BuildResult(new Event { EventId = 1 },
            new Dictionary<string, string> { ["mp_offers"] = "{\"meta\":{\"listingCount\":0,\"ticketCount\":0},\"listings\":[]}" }, null);
        Assert.Empty(r.Listings);
        Assert.Contains("match=yes", r.Coverage);
        Assert.Contains("marketplace has no listings right now", r.Notes);
    }

    [Fact]
    public void Event_url_is_parsed()
    {
        var p = AxsParser.ParseEventUrl("https://www.axs.com/events/1457730/tom-jones-21-event-tickets")!;
        Assert.Equal(1457730, p.Item1);
        Assert.Equal("tom-jones-21-event-tickets", p.Item2);
        Assert.Null(AxsParser.ParseEventUrl("https://example.com/events/1"));
    }

    private static string? Str(JsonElement e) => e.ValueKind == JsonValueKind.Null ? null : e.GetString();
    private static decimal? Num(JsonElement e) => e.ValueKind == JsonValueKind.Null ? null : e.GetDecimal();
}
